/* ============================================================
   MI TAXI RIDERY — Base de datos completa v2.0
   976 entradas: 189 destinos × 4 bases + 220 claves de operación
   ============================================================ */

const DATABASE = {

  // ============================================================
  // DESTINOS ÚNICOS (nombre canónico + sinónimos para voz)
  // ============================================================
  destinos: {
    // ---- MUNICIPIO MARIÑO (numeración 110-190) ----
    '110': { nombre: 'Los Robles (Plaza)', alias: ['los robles', 'robles plaza', 'plaza los robles'], municipio: 'Mariño' },
    '111': { nombre: 'Los Olivos', alias: ['los olivos', 'olivos'], municipio: 'Mariño' },
    '112': { nombre: 'Peña Blanca', alias: ['pena blanca', 'peña blanca'], municipio: 'Mariño' },
    '113': { nombre: 'La Guamachera', alias: ['la guamachera', 'guamachera'], municipio: 'Mariño' },
    '114': { nombre: 'Urb. Manantial', alias: ['manantial', 'urb manantial'], municipio: 'Mariño' },
    '115': { nombre: 'Urb. Oasis', alias: ['oasis', 'urb oasis'], municipio: 'Mariño' },
    '116': { nombre: 'Fundación Mgta.', alias: ['fundacion', 'fundacion margarita'], municipio: 'Mariño' },
    '117': { nombre: 'Portal de los Robles', alias: ['portal los robles', 'portal robles'], municipio: 'Mariño' },
    '118': { nombre: 'Urb. San Fernando', alias: ['san fernando', 'urb san fernando'], municipio: 'Mariño' },
    '119': { nombre: 'Calle de Jardines Mgta.', alias: ['calle jardines', 'jardines margarita'], municipio: 'Mariño' },
    '120': { nombre: 'Urb. Mundo Nuevo', alias: ['mundo nuevo', 'urb mundo nuevo'], municipio: 'Mariño' },
    '121': { nombre: 'Los Chacos', alias: ['los chacos', 'chacos'], municipio: 'Mariño' },
    '122': { nombre: 'Urb. Hugo Chávez F.', alias: ['hugo chavez', 'urb hugo chavez'], municipio: 'Mariño' },
    '123': { nombre: 'Urb. Villa Colonial', alias: ['villa colonial', 'urb villa colonial'], municipio: 'Mariño' },
    '124': { nombre: 'Los Cerritos', alias: ['los cerritos', 'cerritos'], municipio: 'Mariño' },
    '125': { nombre: 'Curiepe', alias: ['curiepe'], municipio: 'Mariño' },
    '126': { nombre: 'Brisas de San Miguel', alias: ['brisas san miguel'], municipio: 'Mariño' },
    '127': { nombre: 'Urb. Brisas del Mar', alias: ['brisas del mar'], municipio: 'Mariño' },
    '128': { nombre: 'Altos de Maneiro', alias: ['altos de maneiro', 'altos maneiro'], municipio: 'Mariño' },
    '129': { nombre: 'El Conchal', alias: ['el conchal', 'conchal'], municipio: 'Mariño' },
    '130': { nombre: 'Urb. Victoria', alias: ['victoria', 'urb victoria'], municipio: 'Mariño' },
    '131': { nombre: 'Casa de Campo', alias: ['casa de campo'], municipio: 'Mariño' },
    '132': { nombre: 'Vistamar', alias: ['vistamar', 'vista mar'], municipio: 'Mariño' },
    '133': { nombre: 'Agua de Vaca (Pampatar)', alias: ['agua de vaca', 'agua vaca', 'agua de vaca pampatar'], municipio: 'Mariño' },
    '134': { nombre: 'El Hato de Agua de Vaca', alias: ['el hato', 'hato agua de vaca'], municipio: 'Mariño' },
    '135': { nombre: 'Apostadero', alias: ['apostadero'], municipio: 'Mariño' },
    '136': { nombre: 'Campeare', alias: ['campeare'], municipio: 'Mariño' },
    '137': { nombre: 'El Potrero', alias: ['el potrero', 'potrero'], municipio: 'Mariño' },
    '138': { nombre: 'Las Casitas (Pampatar)', alias: ['las casitas', 'casitas pampatar'], municipio: 'Mariño' },
    '139': { nombre: 'Punta Ballena', alias: ['punta ballena'], municipio: 'Mariño' },
    '140': { nombre: 'La Caranta (Plaza)', alias: ['la caranta', 'caranta', 'caranta plaza'], municipio: 'Mariño' },
    '141': { nombre: 'Pampatar Fte. Castillo', alias: ['pampatar', 'pampata', 'frente al castillo', 'bahia de pampatar'], municipio: 'Mariño' },
    '142': { nombre: 'Polanco', alias: ['polanco'], municipio: 'Mariño' },
    '143': { nombre: 'Círculo Militar', alias: ['circulo militar'], municipio: 'Mariño' },
    '144': { nombre: 'Paraíso 1', alias: ['paraiso 1', 'paraiso uno'], municipio: 'Mariño' },
    '145': { nombre: 'Paraíso 2', alias: ['paraiso 2', 'paraiso dos'], municipio: 'Mariño' },
    '146': { nombre: 'San Lorenzo', alias: ['san lorenzo'], municipio: 'Mariño' },
    '147': { nombre: 'Moreno', alias: ['moreno'], municipio: 'Mariño' },
    '148': { nombre: 'Playa El Ángel', alias: ['playa el angel', 'el angel'], municipio: 'Mariño' },
    '149': { nombre: 'Urb. Maneiro', alias: ['urb maneiro', 'maneiro'], municipio: 'Mariño' },
    '150': { nombre: 'Urb. Jorge Coll', alias: ['jorge coll'], municipio: 'Mariño' },
    '151': { nombre: 'San Judas Tadeo', alias: ['san judas tadeo', 'san judas'], municipio: 'Mariño' },
    '152': { nombre: 'Av. La Auyama', alias: ['la auyama', 'av auyama', 'avenida auyama'], municipio: 'Mariño' },
    '153': { nombre: 'Urbanismo Luisa C. A.', alias: ['luisa caceres', 'urbanismo luisa'], municipio: 'Mariño' },
    '154': { nombre: 'Costa Azul', alias: ['costa azul'], municipio: 'Mariño' },
    '155': { nombre: 'Av. Bolívar', alias: ['bolivar', 'avenida bolivar', 'av bolivar'], municipio: 'Mariño' },
    '156': { nombre: 'Bahía del Morro', alias: ['bahia del morro', 'bahia morro'], municipio: 'Mariño' },
    '157': { nombre: 'La Arboleda', alias: ['la arboleda', 'arboleda'], municipio: 'Mariño' },
    '158': { nombre: 'Prolongación 4 de Mayo', alias: ['prolongacion 4 mayo', 'prolongacion cuatro de mayo'], municipio: 'Mariño' },
    '159': { nombre: 'La Otra Sábana', alias: ['la otra sabana', 'otra sabana'], municipio: 'Mariño' },
    '160': { nombre: 'Av. 4 de Mayo', alias: ['4 de mayo', 'cuatro de mayo', 'av 4 mayo', 'avenida 4 mayo', 'cuatro mayo'], municipio: 'Mariño' },
    '161': { nombre: 'Urb. Sabanamar', alias: ['sabanamar', 'urb sabanamar'], municipio: 'Mariño' },
    '162': { nombre: 'Vista Bella', alias: ['vista bella'], municipio: 'Mariño' },
    '163': { nombre: 'Los Delfines', alias: ['los delfines', 'delfines'], municipio: 'Mariño' },
    '164': { nombre: 'Campomar', alias: ['campomar'], municipio: 'Mariño' },
    '165': { nombre: 'Bella Vista', alias: ['bella vista'], municipio: 'Mariño' },
    '166': { nombre: 'Guaraguao', alias: ['guaraguao'], municipio: 'Mariño' },
    '167': { nombre: 'Av. Terranova', alias: ['terranova', 'av terranova', 'avenida terranova'], municipio: 'Mariño' },
    '168': { nombre: 'Los Clavelitos', alias: ['los clavelitos', 'clavelitos'], municipio: 'Mariño' },
    '169': { nombre: 'Genovés', alias: ['genoves'], municipio: 'Mariño' },
    '170': { nombre: 'Achipano', alias: ['achipano'], municipio: 'Mariño' },
    '171': { nombre: 'Vicente Marcano', alias: ['vicente marcano'], municipio: 'Mariño' },
    '172': { nombre: 'Cruz Grande', alias: ['cruz grande'], municipio: 'Mariño' },
    '173': { nombre: 'Palguarime', alias: ['palguarime'], municipio: 'Mariño' },
    '174': { nombre: 'El Poblado', alias: ['el poblado', 'poblado'], municipio: 'Mariño' },
    '175': { nombre: 'Calle El Colegio', alias: ['calle el colegio', 'el colegio'], municipio: 'Mariño' },
    '176': { nombre: 'Llano Adentro', alias: ['llano adentro'], municipio: 'Mariño' },
    '177': { nombre: 'Pueblo Nuevo', alias: ['pueblo nuevo'], municipio: 'Mariño' },
    '178': { nombre: 'Fajardo', alias: ['fajardo'], municipio: 'Mariño' },
    '179': { nombre: 'Centro de Porlamar', alias: ['porlamar', 'centro porlamar', 'terminal porlamar', 'centro de porlamar'], municipio: 'Mariño' },
    '180': { nombre: 'La Chacalera', alias: ['la chacalera', 'chacalera'], municipio: 'Mariño' },
    '181': { nombre: 'Conejeros', alias: ['conejeros'], municipio: 'Mariño' },
    '182': { nombre: 'Los Cocos Norte', alias: ['cocos norte', 'los cocos norte'], municipio: 'Mariño' },
    '183': { nombre: 'Los Cocos Sur', alias: ['cocos sur', 'los cocos sur'], municipio: 'Mariño' },
    '184': { nombre: 'Ciudad Cartón', alias: ['ciudad carton'], municipio: 'Mariño' },
    '185': { nombre: 'Los Olivos/Traki', alias: ['los olivos traki', 'traki'], municipio: 'Mariño' },
    '186': { nombre: 'Cerro Colorado', alias: ['cerro colorado'], municipio: 'Mariño' },
    '187': { nombre: 'Charaima (Centro Hispano)', alias: ['charaima', 'centro hispano'], municipio: 'Mariño' },
    '188': { nombre: 'Los Cuatro', alias: ['los cuatro'], municipio: 'Mariño' },
    '189': { nombre: 'El Piache', alias: ['el piache', 'piache'], municipio: 'Mariño' },
    '190': { nombre: 'Macho Muerto', alias: ['macho muerto'], municipio: 'Mariño' },

    // ---- MUNICIPIO GARCÍA (191-221) ----
    '191': { nombre: 'Urb. Luisa C. A.', alias: ['luisa caceres garcia'], municipio: 'García' },
    '192': { nombre: 'El Silguero', alias: ['silguero', 'el silguero'], municipio: 'García' },
    '193': { nombre: 'Villas de Campomar', alias: ['villas campomar'], municipio: 'García' },
    '194': { nombre: 'Isleta 2', alias: ['isleta 2', 'isleta dos'], municipio: 'García' },
    '195': { nombre: 'Isleta Pueblo', alias: ['isleta pueblo', 'isleta'], municipio: 'García' },
    '196': { nombre: 'Doña Elisa', alias: ['dona elisa', 'doña elisa'], municipio: 'García' },
    '197': { nombre: 'Cocopozuelo', alias: ['cocopozuelo'], municipio: 'García' },
    '198': { nombre: 'Urb. Las Marites', alias: ['las marites'], municipio: 'García' },
    '199': { nombre: 'Tricadagas (Las Villas)', alias: ['tricadagas', 'las villas'], municipio: 'García' },
    '200': { nombre: 'San Antonio', alias: ['san antonio'], municipio: 'García' },
    '201': { nombre: 'Villa Charquito', alias: ['villa charquito'], municipio: 'García' },
    '202': { nombre: 'Pedro Luis Briceño', alias: ['pedro luis briceno', 'pedro luis'], municipio: 'García' },
    '203': { nombre: 'Urb. Pueblo Nuevo', alias: ['pueblo nuevo garcia'], municipio: 'García' },
    '204': { nombre: 'Urb. 28 de Mayo', alias: ['28 de mayo', 'veintiocho de mayo'], municipio: 'García' },
    '205': { nombre: 'Villas de San Antonio', alias: ['villas san antonio'], municipio: 'García' },
    '206': { nombre: 'Villa Rosa', alias: ['villa rosa'], municipio: 'García' },
    '207': { nombre: 'Villa Juana', alias: ['villa juana'], municipio: 'García' },
    '208': { nombre: 'Villa Zoita', alias: ['villa zoita'], municipio: 'García' },
    '209': { nombre: 'Portal de la Laguna', alias: ['portal laguna'], municipio: 'García' },
    '210': { nombre: 'Sábana Grande', alias: ['sabana grande'], municipio: 'García' },
    '211': { nombre: 'Conuco Viejo', alias: ['conuco viejo'], municipio: 'García' },
    '212': { nombre: 'Urb. Marisal', alias: ['marisal'], municipio: 'García' },
    '213': { nombre: 'Diario La Hora', alias: ['diario la hora', 'la hora'], municipio: 'García' },
    '214': { nombre: 'Autopista El Valle', alias: ['autopista el valle'], municipio: 'García' },
    '215': { nombre: 'El Valle (Plaza)', alias: ['el valle', 'valle plaza'], municipio: 'García' },
    '216': { nombre: 'Las Piedras del Valle', alias: ['piedras del valle'], municipio: 'García' },
    '217': { nombre: 'Caja de Agua', alias: ['caja de agua'], municipio: 'García' },
    '218': { nombre: 'Toporo', alias: ['toporo'], municipio: 'García' },
    '219': { nombre: 'La Comarca', alias: ['la comarca', 'comarca'], municipio: 'García' },
    '220': { nombre: 'Guatamare', alias: ['guatamare'], municipio: 'García' },
    '221': { nombre: 'UDO', alias: ['udo', 'universidad de oriente'], municipio: 'García' },

    // ---- MUNICIPIO ARISMENDI (222-241) ----
    '222': { nombre: 'La Aguada', alias: ['la aguada', 'aguada'], municipio: 'Arismendi' },
    '223': { nombre: 'La Guarina', alias: ['la guarina', 'guarina'], municipio: 'Arismendi' },
    '224': { nombre: 'Camoruco', alias: ['camoruco'], municipio: 'Arismendi' },
    '225': { nombre: 'Cantarrana', alias: ['cantarrana'], municipio: 'Arismendi' },
    '226': { nombre: 'Santa Lucía', alias: ['santa lucia'], municipio: 'Arismendi' },
    '227': { nombre: 'Barrio El Copey', alias: ['el copey', 'copey'], municipio: 'Arismendi' },
    '228': { nombre: 'La Asunción (Plaza)', alias: ['la asuncion', 'asuncion', 'plaza asuncion'], municipio: 'Arismendi' },
    '229': { nombre: 'Las Casitas', alias: ['las casitas arismendi'], municipio: 'Arismendi' },
    '230': { nombre: 'La Otra Banda', alias: ['la otra banda', 'otra banda'], municipio: 'Arismendi' },
    '231': { nombre: 'Santa Isabel', alias: ['santa isabel'], municipio: 'Arismendi' },
    '232': { nombre: 'El Guayabal', alias: ['el guayabal', 'guayabal'], municipio: 'Arismendi' },
    '233': { nombre: 'Salamanca', alias: ['salamanca'], municipio: 'Arismendi' },
    '234': { nombre: 'Cocheima', alias: ['cocheima'], municipio: 'Arismendi' },
    '236': { nombre: 'Palosano', alias: ['palosano'], municipio: 'Arismendi' },
    '237': { nombre: 'Atamo Sur', alias: ['atamo sur'], municipio: 'Arismendi' },
    '238': { nombre: 'Atamo Norte', alias: ['atamo norte'], municipio: 'Arismendi' },
    '239': { nombre: 'Catálan', alias: ['catalan'], municipio: 'Arismendi' },
    '240': { nombre: 'Chinguirito', alias: ['chinguirito'], municipio: 'Arismendi' },
    '241': { nombre: 'Sábana de Guacuco', alias: ['sabana de guacuco', 'sabana guacuco'], municipio: 'Arismendi' },

    // ---- MUNICIPIO ANTOLÍN DEL CAMPO (242-260) ----
    '242': { nombre: 'Las Tapias', alias: ['las tapias', 'tapias'], municipio: 'Antolín' },
    '243': { nombre: 'La Fuente', alias: ['la fuente', 'fuente'], municipio: 'Antolín' },
    '244': { nombre: 'Urb. El Limón', alias: ['el limon'], municipio: 'Antolín' },
    '245': { nombre: 'Guarame', alias: ['guarame'], municipio: 'Antolín' },
    '246': { nombre: 'Flandes', alias: ['flandes'], municipio: 'Antolín' },
    '247': { nombre: 'La Polvorosa', alias: ['la polvorosa', 'polvorosa'], municipio: 'Antolín' },
    '248': { nombre: 'El Salado', alias: ['el salado', 'salado'], municipio: 'Antolín' },
    '249': { nombre: 'Paraguachi', alias: ['paraguachi'], municipio: 'Antolín' },
    '250': { nombre: 'Guiriguire', alias: ['guiriguire'], municipio: 'Antolín' },
    '251': { nombre: 'La Rinconada', alias: ['la rinconada', 'rinconada'], municipio: 'Antolín' },
    '252': { nombre: 'El Cardón', alias: ['el cardon', 'cardon'], municipio: 'Antolín' },
    '253': { nombre: 'Loma de Guerra', alias: ['loma de guerra'], municipio: 'Antolín' },
    '254': { nombre: 'El Tirano', alias: ['el tirano', 'tirano'], municipio: 'Antolín' },
    '255': { nombre: 'El Toco', alias: ['el toco', 'toco'], municipio: 'Antolín' },
    '256': { nombre: 'Aricagua', alias: ['aricagua'], municipio: 'Antolín' },
    '257': { nombre: 'Cimarrón', alias: ['cimarron'], municipio: 'Antolín' },
    '258': { nombre: 'La Mira', alias: ['la mira', 'mira'], municipio: 'Antolín' },
    '259': { nombre: 'Playa El Agua', alias: ['playa el agua', 'el agua', 'agua playa'], municipio: 'Antolín' },
    '260': { nombre: 'Manzanillo', alias: ['manzanillo'], municipio: 'Antolín' },

    // ---- MUNICIPIO GÓMEZ (261-273) ----
    '261': { nombre: 'Guayacán Norte', alias: ['guayacan norte', 'guayacan'], municipio: 'Gómez' },
    '262': { nombre: 'Pedro González', alias: ['pedro gonzalez', 'pedro gonzales'], municipio: 'Gómez' },
    '263': { nombre: 'Altagracia', alias: ['altagracia'], municipio: 'Gómez' },
    '264': { nombre: 'Las Gamboas', alias: ['las gamboas', 'gamboas'], municipio: 'Gómez' },
    '265': { nombre: 'La Vecindad', alias: ['la vecindad', 'vecindad'], municipio: 'Gómez' },
    '266': { nombre: 'El Sabilar', alias: ['el sabilar', 'sabilar', 'el sabil'], municipio: 'Gómez' },
    '267': { nombre: 'El Maco', alias: ['el maco', 'maco'], municipio: 'Gómez' },
    '268': { nombre: 'Santa Ana', alias: ['santa ana'], municipio: 'Gómez' },
    '269': { nombre: 'El Cercado', alias: ['el cercado', 'cercado'], municipio: 'Gómez' },
    '270': { nombre: 'Tacarigua', alias: ['tacarigua'], municipio: 'Gómez' },
    '271': { nombre: 'San Sebastián', alias: ['san sebastian'], municipio: 'Gómez' },
    '272': { nombre: 'Tacarigüita', alias: ['tacariguita'], municipio: 'Gómez' },
    '273': { nombre: 'El Portachuelo', alias: ['el portachuelo', 'portachuelo', 'mirador'], municipio: 'Gómez' },

    // ---- MUNICIPIO MARCANO (274-279) ----
    '274': { nombre: 'Juan Griego', alias: ['juan griego'], municipio: 'Marcano' },
    '275': { nombre: 'Pedregales', alias: ['pedregales'], municipio: 'Marcano' },
    '276': { nombre: 'Los Millanes', alias: ['los millanes', 'millanes'], municipio: 'Marcano' },
    '277': { nombre: 'Vizcuña', alias: ['vizcuna', 'vizcuña'], municipio: 'Marcano' },
    '278': { nombre: 'Las Cabreras', alias: ['las cabreras', 'cabreras'], municipio: 'Marcano' },
    '279': { nombre: 'Tagüantar', alias: ['taguantar', 'tagüantar', 'taquantar'], municipio: 'Marcano' },

    // ---- MUNICIPIO DÍAZ (280-313) ----
    '280': { nombre: 'La Pista', alias: ['la pista', 'pista'], municipio: 'Díaz' },
    '281': { nombre: 'Boquerón', alias: ['boqueron'], municipio: 'Díaz' },
    '282': { nombre: 'Los Fermines', alias: ['los fermines', 'fermines'], municipio: 'Díaz' },
    '283': { nombre: 'Fuentidueño', alias: ['fuentidueno'], municipio: 'Díaz' },
    '284': { nombre: 'Agua de Vaca (S. Juan)', alias: ['agua de vaca san juan', 'agua vaca san juan'], municipio: 'Díaz' },
    '285': { nombre: 'Mata de Coco', alias: ['mata de coco', 'mata coco'], municipio: 'Díaz' },
    '286': { nombre: 'Guatacaral', alias: ['guatacaral'], municipio: 'Díaz' },
    '287': { nombre: 'Carapacho', alias: ['carapacho'], municipio: 'Díaz' },
    '288': { nombre: 'Guaimeque', alias: ['guaimeque'], municipio: 'Díaz' },
    '289': { nombre: 'Las Barrancas', alias: ['las barrancas', 'barrancas'], municipio: 'Díaz' },
    '290': { nombre: 'Las Villarroeles', alias: ['las villarroeles', 'villarroeles'], municipio: 'Díaz' },
    '291': { nombre: 'La Guardia', alias: ['la guardia', 'guardia'], municipio: 'Díaz' },
    '292': { nombre: 'La Salineta', alias: ['la salineta', 'salineta'], municipio: 'Díaz' },
    '293': { nombre: 'Guiriguire (Díaz)', alias: ['guiriguire diaz'], municipio: 'Díaz' },
    '294': { nombre: 'El Palotal', alias: ['el palotal', 'palotal'], municipio: 'Díaz' },
    '295': { nombre: 'Piedras Negras', alias: ['piedras negras'], municipio: 'Díaz' },
    '296': { nombre: 'La Guarida del Sol', alias: ['la guarida del sol', 'guarida del sol'], municipio: 'Díaz' },
    '297': { nombre: 'La Lagunita', alias: ['la lagunita', 'lagunita'], municipio: 'Díaz' },
    '298': { nombre: 'Cerromar', alias: ['cerromar'], municipio: 'Díaz' },
    '299': { nombre: 'El Espinal', alias: ['el espinal', 'espinal'], municipio: 'Díaz' },
    '300': { nombre: 'Brisas de la Sierra', alias: ['brisas de la sierra', 'brisas sierra'], municipio: 'Díaz' },
    '301': { nombre: 'La Encrucijada', alias: ['la encrucijada', 'encrucijada'], municipio: 'Díaz' },
    '302': { nombre: 'El Dátil', alias: ['el datil', 'datil'], municipio: 'Díaz' },
    '303': { nombre: 'Carcanapiral', alias: ['carcanapiral'], municipio: 'Díaz' },
    '304': { nombre: 'Nueva Segovia', alias: ['nueva segovia'], municipio: 'Díaz' },
    '305': { nombre: 'Valle Verde (Bloques)', alias: ['valle verde', 'valle verde bloques'], municipio: 'Díaz' },
    '306': { nombre: 'La Capilla (Valle Verde)', alias: ['la capilla', 'capilla valle verde'], municipio: 'Díaz' },
    '307': { nombre: 'Las Maritas (Valle Verde)', alias: ['las maritas', 'maritas valle verde'], municipio: 'Díaz' },
    '308': { nombre: 'Cotoperíz', alias: ['cotoperiz'], municipio: 'Díaz' },
    '309': { nombre: 'Los Bagres', alias: ['los bagres', 'bagres'], municipio: 'Díaz' },
    '310': { nombre: 'Las Bermúdez', alias: ['las bermudez', 'bermudez'], municipio: 'Díaz' },
    '311': { nombre: 'El Yaque', alias: ['el yaque', 'yaque', 'playa el yaque'], municipio: 'Díaz' },
    '312': { nombre: 'Las Guevaras', alias: ['las guevaras', 'guevaras'], municipio: 'Díaz' },
    '313': { nombre: 'Brisas del Valle', alias: ['brisas del valle'], municipio: 'Díaz' },

    // ---- MUNICIPIO TUBORES (314-329) ----
    '314': { nombre: 'Las Giles', alias: ['las giles', 'giles'], municipio: 'Tubores' },
    '315': { nombre: 'Guayacán Sur', alias: ['guayacan sur'], municipio: 'Tubores' },
    '316': { nombre: 'Las Marvales', alias: ['las marvales', 'marvales'], municipio: 'Tubores' },
    '317': { nombre: 'Las Hernández', alias: ['las hernandez', 'hernandez'], municipio: 'Tubores' },
    '318': { nombre: 'Las Cubas', alias: ['las cubas', 'cubas'], municipio: 'Tubores' },
    '319': { nombre: 'Orinoco', alias: ['orinoco'], municipio: 'Tubores' },
    '320': { nombre: 'La Blanquilla', alias: ['la blanquilla', 'blanquilla'], municipio: 'Tubores' },
    '321': { nombre: 'Pueblo El Guamache', alias: ['el guamache pueblo', 'guamache pueblo'], municipio: 'Tubores' },
    '322': { nombre: 'Punta de Mangle', alias: ['punta de mangle'], municipio: 'Tubores' },
    '323': { nombre: 'Las Lares', alias: ['las lares', 'lares'], municipio: 'Tubores' },
    '324': { nombre: 'Los Gómez', alias: ['los gomez', 'gomez'], municipio: 'Tubores' },
    '325': { nombre: 'Santa María', alias: ['santa maria'], municipio: 'Tubores' },
    '326': { nombre: 'Laguna de Raya', alias: ['laguna de raya', 'laguna raya'], municipio: 'Tubores' },
    '327': { nombre: 'Mata Redonda', alias: ['mata redonda'], municipio: 'Tubores' },
    '328': { nombre: 'Chacachacare', alias: ['chacachacare'], municipio: 'Tubores' },
    '329': { nombre: 'La Restinga', alias: ['la restinga', 'restinga'], municipio: 'Tubores' },

    // ---- MUNICIPIO PENÍNSULA DE MACANAO (330-340) ----
    '330': { nombre: 'Boca del Río', alias: ['boca del rio', 'boca rio'], municipio: 'Macanao' },
    '331': { nombre: 'La Yegua', alias: ['la yegua', 'yegua'], municipio: 'Macanao' },
    '332': { nombre: 'Guayacancito', alias: ['guayacancito'], municipio: 'Macanao' },
    '333': { nombre: 'El Horcón', alias: ['el horcon', 'horcon'], municipio: 'Macanao' },
    '334': { nombre: 'El Manglillo', alias: ['el manglillo', 'manglillo'], municipio: 'Macanao' },
    '335': { nombre: 'Boca Chica', alias: ['boca chica'], municipio: 'Macanao' },
    '336': { nombre: 'Punta Arenas', alias: ['punta arenas'], municipio: 'Macanao' },
    '337': { nombre: 'Boca de Pozo', alias: ['boca de pozo', 'boca pozo'], municipio: 'Macanao' },
    '338': { nombre: 'Robledal', alias: ['robledal', 'robleda'], municipio: 'Macanao' },
    '339': { nombre: 'La Pared', alias: ['la pared', 'pared'],